// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: protos/grpcdemo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BarkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Age     int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *BarkRequest) Reset() {
	*x = BarkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_grpcdemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarkRequest) ProtoMessage() {}

func (x *BarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grpcdemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarkRequest.ProtoReflect.Descriptor instead.
func (*BarkRequest) Descriptor() ([]byte, []int) {
	return file_protos_grpcdemo_proto_rawDescGZIP(), []int{0}
}

func (x *BarkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BarkRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BarkRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type BarkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Out string `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
}

func (x *BarkResponse) Reset() {
	*x = BarkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_grpcdemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarkResponse) ProtoMessage() {}

func (x *BarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grpcdemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarkResponse.ProtoReflect.Descriptor instead.
func (*BarkResponse) Descriptor() ([]byte, []int) {
	return file_protos_grpcdemo_proto_rawDescGZIP(), []int{1}
}

func (x *BarkResponse) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

var File_protos_grpcdemo_proto protoreflect.FileDescriptor

var file_protos_grpcdemo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d,
	0x0a, 0x0b, 0x42, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a,
	0x0c, 0x42, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x32,
	0x3f, 0x0a, 0x0d, 0x44, 0x6f, 0x67, 0x53, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x2e, 0x0a, 0x03, 0x53, 0x61, 0x79, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_grpcdemo_proto_rawDescOnce sync.Once
	file_protos_grpcdemo_proto_rawDescData = file_protos_grpcdemo_proto_rawDesc
)

func file_protos_grpcdemo_proto_rawDescGZIP() []byte {
	file_protos_grpcdemo_proto_rawDescOnce.Do(func() {
		file_protos_grpcdemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_grpcdemo_proto_rawDescData)
	})
	return file_protos_grpcdemo_proto_rawDescData
}

var file_protos_grpcdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_grpcdemo_proto_goTypes = []interface{}{
	(*BarkRequest)(nil),  // 0: proto.BarkRequest
	(*BarkResponse)(nil), // 1: proto.BarkResponse
}
var file_protos_grpcdemo_proto_depIdxs = []int32{
	0, // 0: proto.DogSayService.Say:input_type -> proto.BarkRequest
	1, // 1: proto.DogSayService.Say:output_type -> proto.BarkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_grpcdemo_proto_init() }
func file_protos_grpcdemo_proto_init() {
	if File_protos_grpcdemo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_grpcdemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_grpcdemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_grpcdemo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_grpcdemo_proto_goTypes,
		DependencyIndexes: file_protos_grpcdemo_proto_depIdxs,
		MessageInfos:      file_protos_grpcdemo_proto_msgTypes,
	}.Build()
	File_protos_grpcdemo_proto = out.File
	file_protos_grpcdemo_proto_rawDesc = nil
	file_protos_grpcdemo_proto_goTypes = nil
	file_protos_grpcdemo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DogSayServiceClient is the client API for DogSayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DogSayServiceClient interface {
	Say(ctx context.Context, in *BarkRequest, opts ...grpc.CallOption) (*BarkResponse, error)
}

type dogSayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDogSayServiceClient(cc grpc.ClientConnInterface) DogSayServiceClient {
	return &dogSayServiceClient{cc}
}

func (c *dogSayServiceClient) Say(ctx context.Context, in *BarkRequest, opts ...grpc.CallOption) (*BarkResponse, error) {
	out := new(BarkResponse)
	err := c.cc.Invoke(ctx, "/proto.DogSayService/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DogSayServiceServer is the server API for DogSayService service.
type DogSayServiceServer interface {
	Say(context.Context, *BarkRequest) (*BarkResponse, error)
}

// UnimplementedDogSayServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDogSayServiceServer struct {
}

func (*UnimplementedDogSayServiceServer) Say(context.Context, *BarkRequest) (*BarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}

func RegisterDogSayServiceServer(s *grpc.Server, srv DogSayServiceServer) {
	s.RegisterService(&_DogSayService_serviceDesc, srv)
}

func _DogSayService_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogSayServiceServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DogSayService/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogSayServiceServer).Say(ctx, req.(*BarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DogSayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DogSayService",
	HandlerType: (*DogSayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _DogSayService_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/grpcdemo.proto",
}
